### ISSUE TITLE
oid is not set

### ISSUE THREAD

**Issue by driesvanhaver** [lukeyouell/craft-salesforceleads#2]
Dear I've tried out the plugin but oid is not set via the settings tab. Even if I add the oid manually into the form code it won't post.

My form:
```
<form action="" method="post">

  {{ csrfInput() }}
  <input type="hidden" name="action" value="salesforce-leads/post">
  <input type="hidden" name="lead_source" value="{{ 'Web'|hash }}">
  <input type="hidden" name="Campaign_ID" value="{{ '00B0Q000000U9XmUAK'|hash }}" >
  <label>Name</label>
  <input type="text" name="name">

  <label>Email Address</label>
  <input type="email" name="email">
  
  <input type="text" name="test" value="Halllo">


  <input type="submit" value="Submit">

</form>
```
My response: 
`{"success":true,"statusCode":200,"reason":"OK","body":"\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\n<html>\n<head>\n<meta HTTP-EQUIV=\"PRAGMA\" CONTENT=\"NO-CACHE\">\n<meta http-equiv=\"Refresh\" content=\"0; URL=http://local.tourneepedale.be/nl/\">\n</head>\n<script>if (this.SfdcApp && this.SfdcApp.projectOneNavigator) { SfdcApp.projectOneNavigator.handleRedirect('http://local.tourneepedale.be/nl/'); }  else if (window.location.replace){ window.location.replace('http://local.tourneepedale.be/nl/');} else {;window.location.href ='http://local.tourneepedale.be/nl/';} </script></html>\n","payload":{"lead_source":"Web","Campaign_ID":"00B0Q000000U9XmUAK","name":"Dries Van haver","email":"dries@lavagraphics.be","test":"Halllo","retURL":"http://local.tourneepedale.be/nl/"}}`

**Comment by lukeyouell** [comment]
@driesvanhaver are you using > 1.1.3? There was an issue with the OID value that was fixed.

It's worth noting that the OID isn't returned in the response anymore to prevent it being exposed to the user.
